version: '3'

services:
  mariadb-instance:
    image: mariadb:latest
    container_name: mariadb-instance
    volumes:
      - mariadb-volume:/var/lib/mysql:Z
    environment:
      - MARIADB_DATABASE=satoru
      - MARIADB_ROOT_PASSWORD=strongest-one
    ports:
      - "3306:3306"
  fastapi:
    depends_on:
      - mariadb-instance
    build: ./server/
    container_name: satoru-fastapi
    command: sh -c "sleep 10 && uvicorn main:app --host 0.0.0.0 --port 8000"
    environment:
      - MARIADB_USER=root
      - MARIADB_PORT=3306
      - MARIADB_HOST=mariadb-instance
      - MARIADB_PASSWORD=strongest-one
      - MARIADB_DATABASE_NAME=satoru
      - CRYPTO_ALGORITHM=HS256
      - CRYPTO_SECRET_KEY=P0oWNbNlfvbDwPZZ
      - CRYPTO_ACCESS_TOKEN_EXPIRE_MINUTES=600
    ports:
      - "8000:8000"
  vue:
    container_name: satoru-vue
    build:
      context: ./client/
    command: sh -c "uvicorn server:app --host 0.0.0.0 --port 4242"
    ports:
      - 4242:4242

volumes:
  mariadb-volume:
