version: '3'

services:
  api:
    build: .
    container_name: satoru-api
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 80 --ssl-keyfile certs/key.pem --ssl-certfile certs/certificate.pem"
    env_file:
      - .env
    ports:
      - 80:80